# Migrated to TOML from https://gist.github.com/r-darwish/f8bb21a6c89a02c4bef76cc38bddad39
# Credits to r-darwish for creating the theme

[colors.primary]
background = "0x1e2127"
foreground = "0xabb2bf"
bright_foreground = "0xe6efff"

[colors.normal]
black = "0x1e2127"
red = "0xe06c75"
green = "0x98c379"
yellow = "0xd19a66"
blue = "0x61afef"
magenta = "0xc678dd"
cyan = "0x56b6c2"
white = "0x828791"

[colors.bright]
black = "0x5c6370"
red = "0xe06c75"
green = "0x98c379"
yellow = "0xd19a66"
blue = "0x61afef"
magenta = "0xc678dd"
cyan = "0x56b6c2"
white = "0xe6efff"

[colors.dim]
black = "0x1e2127"
red = "0xe06c75"
green = "0x98c379"
yellow = "0xd19a66"
blue = "0x61afef"
magenta = "0xc678dd"
cyan = "0x56b6c2"
white = "0x828791"
