# Default colors
[colors.primary]
background = "#161821"
foreground = "#c6c8d1"

# Cursor colors
[colors.cursor]
text = "#161821"
cursor = "#c6c8d1"

# Selection colors
[colors.selection]
text = "CellForeground"
background = "#272c42"

# Normal colors
[colors.normal]
black = "#1e2132"
red = "#e27878"
green = "#b4be82"
yellow = "#e2a478"
blue = "#84a0c6"
magenta = "#a093c7"
cyan = "#89b8c2"
white = "#c6c8d1"

# Bright colors
[colors.bright]
black = "#6b7089"
red = "#e98989"
green = "#c0ca8e"
yellow = "#e9b189"
blue = "#91acd1"
magenta = "#ada0d3"
cyan = "#95c4ce"
white = "#d2d4de"
